name: bug-reporting-system
services:
- name: backend
  source_dir: /backend
  github:
    repo: Epik-Whale463/bug-reporting-system
    branch: main
  dockerfile_path: backend/Dockerfile
  build_command: ""
  run_command: "gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  envs:
  - key: DEBUG
    value: "False"
  - key: ALLOWED_HOSTS
    value: "*"
  - key: DJANGO_SETTINGS_MODULE
    value: "backend.settings"
  routes:
  - path: /api

- name: frontend
  source_dir: /frontend
  github:
    repo: Epik-Whale463/bug-reporting-system
    branch: main
  dockerfile_path: frontend/Dockerfile
  build_command: "npm run build"
  run_command: "npm run start"
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  envs:
  - key: NEXT_PUBLIC_API_URL
    value: "${backend.PUBLIC_URL}/api"
  - key: NODE_ENV
    value: "production"
  routes:
  - path: /

databases:
- name: db
  engine: PG
  version: "14"
  size: basic-xxs

workers: []